### ISSUE TITLE
pysnooper cant deco async funciton

### ISSUE THREAD

**Issue by ydf0509** [cool-RR/PySnooper#211] opened 2021-01-20 03:34 UTC
```
@snoop(depth=1000,)
async def af():
        async with aiohttp.request('get', url='https://www.baidu.com') as resp:
            text = await resp.text()
            print(text)


if __name__ == '__main__':
     asyncio.get_event_loop().run_until_complete(af())
```

this will be error.pycnooper cant decorate async function

**Comment by cool-RR** [comment] 2021-01-20 05:28
Duplicate of #27

**Closed by cool-RR** 2021-01-20 05:28 UTC
