### ISSUE TITLE
pysnooper/tracer.py", line 75, in get_source_from_frame     raise NotImplementedError

### ISSUE THREAD

**Issue by ouening** [cool-RR/PySnooper#20] opened 2019-04-23 07:21 UTC
When I ran a simple script:

```
import pysnooper
import numpy as np

@pysnooper.snoop()
def multi_matmul(times):
    x = np.random.rand(2,2)
    w = np.random.rand(2,2)
    
    for i in range(times):
        x = np.matmul(x,w)
    return x

multi_matmul(3)
```

The error happened:

```
Starting var:.. times = 3
Traceback (most recent call last):
  File "<tmp 1>", line 14, in <module>
    multi_matmul(3)
  File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-121>", line 2, in multi_matmul
  File "/usr/local/lib/python3.6/dist-packages/pysnooper/pysnooper.py", line 72, in decorate
    return function(*args, **kwargs)
  File "<tmp 1>", line 4, in multi_matmul
    @pysnooper.snoop()
  File "/usr/local/lib/python3.6/dist-packages/pysnooper/tracer.py", line 182, in trace
    source_line = get_source_from_frame(frame)[frame.f_lineno - 1]
  File "/usr/local/lib/python3.6/dist-packages/pysnooper/tracer.py", line 75, in get_source_from_frame
    raise NotImplementedError
NotImplementedError
```

**Comment by cool-RR** [comment] 2019-04-23 08:16
I tried your example and it worked perfectly for me.

Could you please try this and tell me the output:

    import numpy
    print(numpy)

**Comment by pLOPeGG** [comment] 2019-04-23 08:51
Same bug here with the code provided in the readme:
```
import pysnooper

@pysnooper.snoop()
def number_to_bits(number):
    if number:
        bits = []
        while number:
            number, remainder = divmod(number, 2)
            bits.insert(0, remainder)
        return bits
    else:
        return [0]

number_to_bits(6)
```
And the related error:
```
<ipython-input-33-d9086aeb58cb> in <module>
     12         return [0]
     13
---> 14 number_to_bits(6)

<decorator-gen-124> in number_to_bits(number)

~\AppData\Local\Continuum\anaconda3\envs\ENV\lib\site-packages\pysnooper\pysnooper.py in decorate(function, *args, **kwargs)
     70                     write=write, variables=variables,
     71                     depth=depth, prefix=prefix):
---> 72             return function(*args, **kwargs)
     73
     74     return decorate

<ipython-input-33-d9086aeb58cb> in number_to_bits(number)
      1 import pysnooper
      2
----> 3 @pysnooper.snoop()
      4 def number_to_bits(number):
      5     if number:

~\AppData\Local\Continuum\anaconda3\envs\ENV\lib\site-packages\pysnooper\tracer.py in trace(self, frame, event, arg)
    182
    183         now_string = datetime_module.datetime.now().time().isoformat()
--> 184         source_line = get_source_from_frame(frame)[frame.f_lineno - 1]
    185         self.write('{indent}{now_string} {event:9} '
    186                    '{frame.f_lineno:4} {source_line}'.format(**locals()))

~\AppData\Local\Continuum\anaconda3\envs\ENV\lib\site-packages\pysnooper\tracer.py in get_source_from_frame(frame)
     75             pass
     76     if source is None:
---> 77         raise NotImplementedError
     78
     79     # If we just read the source from a file, or if the loader did not

NotImplementedError:
```

**Comment by cool-RR** [comment] 2019-04-23 08:56
This isn't about the code, it's about your setup. Please see my previous comment and give me the output of that.

**Comment by pLOPeGG** [comment] 2019-04-23 09:00
Here it goes:

```
In [34]: import numpy

In [35]: print(numpy)
<module 'numpy' from 'C:\\Users\\******\\AppData\\Local\\Continuum\\anaconda3\\envs\\ENV\\lib\\site-packages\\numpy\\__init__.py'>
```

**Comment by cool-RR** [comment] 2019-04-23 09:04
Are the **** in the original, or did you censor your username?

**Comment by pLOPeGG** [comment] 2019-04-23 09:05
Oh yes it's just my username, containing ASCII caracters only. I did the same for `ENV`.

**Comment by cool-RR** [comment] 2019-04-23 09:12
Thanks. I could help with this, but it's going to be a bit difficult because it's related to your environment. If you're interested in doing some checks for me, that could help.

`tracer.py` has these lines:

    source = None
    if hasattr(loader, 'get_source'):
        try:
            source = loader.get_source(module_name)
        except ImportError:
            pass
        if source is not None:
            source = source.splitlines()
    if source is None:
        try:
            with open(file_name, 'rb') as fp:
                source = fp.read().splitlines()
        except (OSError, IOError):
            pass
    if source is None:
        raise NotImplementedError

I want you to figure out what's going on in your machine. Is `hasattr(loader, 'get_source')` false? Or maybe the `open` line below fails for some reason? 

It'll be difficult for you to use a debugger, because PySnooper overrides the trace function. You can find these things by modifying the `tracer.py` and causing it to print the exceptions, possibly to a file.

If you're into doing the above, we might be able to fix these problems.

**Comment by pLOPeGG** [comment] 2019-04-23 09:14
Seems fine to me, I'm going to check this for you

**Comment by pLOPeGG** [comment] 2019-04-23 09:24
I added some log in the `tracer.py` file:

```
source = None
    # Begin of log
    with open(R'C:\Users\******\AppData\Local\Continuum\anaconda3\envs\ENV\Lib\site-packages\pysnooper\log.txt', 'w+') as fp:
        fp.write(str(hasattr(loader, 'get_source')))
        fp.write('\n')
    # End of log
    if hasattr(loader, 'get_source'):
        try:
            source = loader.get_source(module_name)
        except ImportError:
            pass
        if source is not None:
            source = source.splitlines()
```

And indeed `hasattr(loader, 'get_source')` is `False`

**Comment by cool-RR** [comment] 2019-04-23 09:26
Good, now I want the exception from the file read.

**Comment by pLOPeGG** [comment] 2019-04-23 09:32
So the `str(error)` provides this:

`[Errno 22] Invalid argument: '<ipython-input-1-d9086aeb58cb>'`

What field do you want ?

**Comment by cool-RR** [comment] 2019-04-23 09:34
Ah, I think I get it. Are you using PySnooper on code that you're typing in the interactive shell?

**Comment by pLOPeGG** [comment] 2019-04-23 09:35
Yes indeed I'm testing it on IPython, going to test without REPL

**Comment by YubinXie** [comment] 2019-04-23 14:55
![3399428E-1CF4-478C-8B98-F0D6F083166A](https://user-images.githubusercontent.com/16257776/56591127-30482b00-65b6-11e9-9bdc-1406c8888a4c.png)

I have the same error in Mac OS using Jupyter lab.

```
import numpy
print(numpy)
<module 'numpy' from '/Users/name/miniconda3/lib/python3.6/site-packages/numpy/__init__.py'>
```

**Comment by cool-RR** [comment] 2019-04-23 16:31
Makes sense. Guys, if you want this to be fixed, I need you to find how to
get the code from an iPython shell or a Jupyter notebook. If it's possible,
send me the code and I could add that it to PySnooper.

**Comment by wangzz313** [comment] 2019-04-24 07:21
jupyter-notebook can not work but other well..

**Comment by cool-RR** [comment] 2019-04-24 11:00
Duplicate of #16

**Closed** 2019-04-24 11:00 UTC

**Comment by cool-RR** [comment] 2019-04-24 19:38
@ouening @pLOPeGG @YubinXie  @wangzz313  PySnooper now works in Jupyter and IPython :)

**Comment by YubinXie** [comment] 2019-04-24 19:40
Confirmed. Thanks!

**Comment by ouening** [comment] 2019-04-25 01:31
OS: Ubuntu 18.04
python:

@cool-RR I tried in ipython and qtconsole, it didn't work. Errors shows below:
```

Jupyter QtConsole 4.4.3
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pysnooper
   ...: 
   ...: @pysnooper.snoop()
   ...: def number_to_bits(number):
   ...:     if number:
   ...:         bits = []
   ...:         while number:
   ...:             number, remainder = divmod(number, 2)
   ...:             bits.insert(0, remainder)
   ...:         return bits
   ...:     else:
   ...:         return [0]
   ...: 
   ...: number_to_bits(6)
Starting var:.. number = 6
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-1-d9086aeb58cb> in <module>
     12         return [0]
     13 
---> 14 number_to_bits(6)

</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-127> in number_to_bits(number)

/usr/local/lib/python3.6/dist-packages/pysnooper/pysnooper.py in decorate(function, *args, **kwargs)
     70                     write=write, variables=variables,
     71                     depth=depth, prefix=prefix):
---> 72             return function(*args, **kwargs)
     73 
     74     return decorate

<ipython-input-1-d9086aeb58cb> in number_to_bits(number)
      1 import pysnooper
      2 
----> 3 @pysnooper.snoop()
      4 def number_to_bits(number):
      5     if number:

/usr/local/lib/python3.6/dist-packages/pysnooper/tracer.py in trace(self, frame, event, arg)
    180 
    181         now_string = datetime_module.datetime.now().time().isoformat()
--> 182         source_line = get_source_from_frame(frame)[frame.f_lineno - 1]
    183         self.write('{indent}{now_string} {event:9} '
    184                    '{frame.f_lineno:4} {source_line}'.format(**locals()))

/usr/local/lib/python3.6/dist-packages/pysnooper/tracer.py in get_source_from_frame(frame)
     73             pass
     74     if source is None:
---> 75         raise NotImplementedError
     76 
     77     # If we just read the source from a file, or if the loader did not

NotImplementedError: 

In [2]: 
```

And about the first problem, I ran the code in pyzo and didn't save the file before. When I saved the file it worked. It's strange!

**Comment by cool-RR** [comment] 2019-04-25 06:25
I think you forgot to upgrade PySnooper.
