### ISSUE TITLE
Feature request: Support generators

### ISSUE THREAD

**Issue by zengxiaofei** [cool-RR/PySnooper#9] opened 2019-04-22 16:50 UTC
For example:

```Python
from __future__ import print_function
import pysnooper

@pysnooper.snoop()
def fib(max_n):
    a, b = 0, 1
    while a < max_n:
        yield a
        a, b = b, a + b

def main():
    for n in fib(4):
        print(n)

if __name__ == '__main__':
    main()
```

Output:

```Bash
$ python mytest.py 
0
1
1
2
3
```

**Comment by cool-RR** [comment] 2019-04-22 16:56
Correct. That would be a good feature to implement. Feel free to send a pull request!

**Comment by cool-RR** [comment] 2019-05-02 18:39
Duplicate of #44

**Closed by cool-RR** 2019-05-02 18:39 UTC
